# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

start-at-login = true

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Start borders
# currently handled by system service
# after-startup-command = [
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# ]

[mode.main.binding]
alt-enter = 'exec-and-forget open -na /Applications/Ghostty.app'
alt-shift-enter = 'exec-and-forget open -na /Applications/Firefox.app'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-b = 'split horizontal'
alt-v = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles accordion' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-tab = 'workspace-back-and-forth'

alt-q = 'workspace Browser'
alt-c = 'workspace Code'
alt-t = 'workspace Terminal'
alt-z = 'workspace Zotero'
alt-m = 'workspace Messaging'

alt-shift-q = 'move-node-to-workspace Browser'
alt-shift-c = 'move-node-to-workspace Code'
alt-shift-t = 'move-node-to-workspace Terminal'
alt-shift-z = 'move-node-to-workspace Zotero'
alt-shift-m = 'move-node-to-workspace Messaging'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-n = 'move-workspace-to-monitor --wrap-around next'
alt-shift-p = 'move-workspace-to-monitor --wrap-around prev'

alt-shift-r = 'reload-config'

alt-r = 'mode resize'

[gaps]
outer.left = 7
outer.right = 7
outer.top = 7
outer.bottom = 7
inner.horizontal = 10
inner.vertical = 10


[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['layout floating']  # The callback itself

[[on-window-detected]]
# if.app-id = 'com.larksuite.larkApp.iron'
if.window-title-regex-substring = 'Lark Meetings'
run = ['move-node-to-workspace 6'] 

[[on-window-detected]]
if.app-id = 'com.larksuite.larkApp'
run = ['move-node-to-workspace 10']  
