#!/bin/sh

usage(){
    echo "Sets backgrounds for desktop/lockscreen and applies specified wal theme engine"
    echo "Usage: setbg <light|dark> <haishoku|colorz|wal|schemer2|colorthief> </path/to/wallpaper>"
}


setlight(){
    wal -l -n --backend "$1" -i "$2" -q
    echo "$(pwd)/$2" > ~/.wallpaper
    feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"
    convert_dir="/usr/share/backgrounds/$2"
    #sudo convert "$2" -resize 1920x1080 $(echo "$convert_dir")
    #sudo convert "$2" -resize 1920x1080 "$(echo $convert_dir)"
    reload_dunst.sh
    #sudo convert "$2" -resize 1920x1080 -blur 0x8 /usr/share/lightdm-webkit/themes/modern/bg-blurred
}

setdark(){
    wal -n --backend "$1" -i "$2" -q
    echo "$(pwd)/$2" > ~/.wallpaper
    feh --bg-scale "$(< "${HOME}/.cache/wal/wal")"
    convert_dir="/usr/share/backgrounds/$2"
    #echo "sudo convert "$2" -resize 1920x1080 \"$(echo $convert_dir)\""
    #sudo convert "$2" -resize 1920x1080 "$(echo $convert_dir)"
    reload_dunst.sh
	#sudo convert "$2" -resize 1920x1080 -blur 0x8 /usr/share/lightdm-webkit/themes/modern/bg-blurred 
}

if [ $# != 3 ]; then
    usage
    exit 1
else
    case $1 in
        light) setlight $2 $3;;
        dark)  setdark $2 $3;;
        *)     usage; exit 1;;
    esac
fi


